version: "2"

formatters:
  enable:
    - gci
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    gofumpt:
      extra-rules: true

linters:
  enable:
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - depguard
    - dupl
    - durationcheck
    - err113
    - errname
    - exhaustive
    - goconst
    - gocritic
    - gosec
    - iface
    - ineffassign
    - intrange
    - mirror
    - modernize
    - nolintlint
    - noctx
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - promlinter
    - staticcheck
    - tagalign
    - testifylint
    - thelper
    - tparallel
    - thelper
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - zerologlint
  settings:
    copyloopvar:
      check-alias: true
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/rs/zerolog/log"
              desc: use an explicit logger
    gocritic:
      enable-all: true
      disabled-checks:
        - httpNoBody
        - whyNoLint
    promlinter:
      strict: true

  exclusions:
    paths:
      - ".*_gen.go"
      - ".*_gen_test.go"
