name: package

on:
  workflow_call:

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
          filter: tree:0
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
        with:
          go-version: stable

      - name: Generate code
        run: go generate ./...

      - name: Package binary
        run: SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) ./.github/scripts/package.sh

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
        with:
          name: locaccel-packages
          path: dist/*
          if-no-files-found: error
