name: package

on:
  workflow_call:

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          fetch-tags: true
          filter: tree:0
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16  # v6.5.0
        with:
          go-version: stable

      - name: Generate code
        run: go generate ./...

      - name: Package binary
        run: SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) ./.github/scripts/package.sh

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: locaccel-packages
          path: dist/*
          if-no-files-found: error
